- name: Restart auditd
  ansible.builtin.systemd_service:
    name: auditd
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted

- name: Update grub
  ansible.builtin.command:
    cmd: update-grub
  changed_when: true
