- name: "{{ apt_repository_name }} | deploy signing key"
  ansible.builtin.copy:
    content: "{{ apt_repository_key }}"
    dest: "/etc/apt/keyrings/{{ apt_repository_key_id }}.asc"
    owner: root
    group: root
    mode: "0644"

- name: "{{ apt_repository_name }} | deploy repository source"
  ansible.builtin.template:
    src: etc/apt/sources.list.d/repo.list.j2
    dest: "/etc/apt/sources.list.d/{{ apt_repository_name }}.list"
    owner: root
    group: root
    mode: "0644"
  notify: Update apt cache

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
